@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":CreateStoreController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "cityRepository\n:cityRepository" as cityRepository

-> CTRL : getcities()
                activate CTRL

                    CTRL -> PLAT : getcitiesRepository()
                    activate PLAT

                    PLAT --> CTRL: cityRepository
                    deactivate PLAT

                    CTRL -> cityRepository : getcities()
                    activate cityRepository

                    cityRepository --> CTRL : citiesList
                    deactivate cityRepository
                    <--CTRL : citiesList
                deactivate CTRL

@enduml