@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PublishAnnouncementController" as Controller
participant "Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as RepositoryInstance
participant "announcementCategoryRepository:\nAnnouncementCategoryRepository" as AnnouncementRepository

autonumber 21
-> Controller : getAnnouncementCategoryByDescription()
autonumber 21.1
activate Controller

    group Get Announcement Category Object

        Controller -> RepositoryInstance: getAnnouncementCategoryRepository()
        activate RepositoryInstance

            RepositoryInstance --> Controller: announcementCategoryRepository
        deactivate RepositoryInstance

        Controller -> AnnouncementRepository: getAnnouncementCategoryByDescription(announcementCategoryDescription)
        activate AnnouncementRepository

            AnnouncementRepository --> Controller: announcementCategory
        deactivate AnnouncementRepository

    end
    autonumber 22
    <-- Controller : announcementCategory
deactivate Controller

@enduml